# Generated by Django 5.2.8 on 2026-03-30 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_guild_mission_templates(apps, schema_editor):
    GuildMissionTemplate = apps.get_model("guilds", "GuildMissionTemplate")

    GuildMissionTemplate.objects.update_or_create(
        key="guild_patrol_alpha",
        defaults={
            "name": "帮会巡逻·甲",
            "description": "初级巡逻任务，适合新人帮会快速积累收益。",
            "difficulty": "junior",
            "task_type": "patrol",
            "base_duration_seconds": 600,
            "ruby_reward": 20,
            "recommended_guest_count": 2,
            "allow_troops": False,
            "enemy_guests": [],
            "enemy_troops": {},
            "enemy_technology": {},
            "is_active": False,
            "sort_weight": 10,
        },
    )
    GuildMissionTemplate.objects.update_or_create(
        key="guild_supply_escort",
        defaults={
            "name": "帮会押运补给",
            "description": "中级押运任务，可携带护院，途中会遭遇弓兵袭扰。",
            "difficulty": "intermediate",
            "task_type": "escort",
            "base_duration_seconds": 1200,
            "ruby_reward": 45,
            "recommended_guest_count": 3,
            "allow_troops": True,
            "enemy_guests": [],
            "enemy_troops": {"archer": 80},
            "enemy_technology": {"combat": 1},
            "is_active": False,
            "sort_weight": 20,
        },
    )


def rollback_seed_guild_mission_templates(apps, schema_editor):
    GuildMissionTemplate = apps.get_model("guilds", "GuildMissionTemplate")
    GuildMissionTemplate.objects.filter(key__in=["guild_patrol_alpha", "guild_supply_escort"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_add_player_troop"),
        ("guilds", "0007_remove_guildheropoolentry_ghp_guild_exp_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildMissionTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(unique=True, verbose_name="任务标识")),
                ("name", models.CharField(max_length=64, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("junior", "初级"), ("intermediate", "中级"), ("advanced", "高级")],
                        default="junior",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("patrol", "巡逻"), ("escort", "押运"), ("suppress", "讨伐")],
                        default="patrol",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                ("base_duration_seconds", models.PositiveIntegerField(default=600, verbose_name="基础耗时(秒)")),
                ("ruby_reward", models.PositiveIntegerField(default=0, verbose_name="红宝石奖励")),
                ("recommended_guest_count", models.PositiveSmallIntegerField(default=1, verbose_name="推荐门客数")),
                ("allow_troops", models.BooleanField(default=False, verbose_name="允许携带护院")),
                ("enemy_guests", models.JSONField(blank=True, default=list, verbose_name="敌方门客配置")),
                ("enemy_troops", models.JSONField(blank=True, default=dict, verbose_name="敌方护院配置")),
                ("enemy_technology", models.JSONField(blank=True, default=dict, verbose_name="敌方科技配置")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort_weight", models.IntegerField(default=0, verbose_name="排序权重")),
            ],
            options={
                "verbose_name": "帮会任务模板",
                "verbose_name_plural": "帮会任务模板",
                "db_table": "guild_mission_templates",
                "ordering": ["-is_active", "sort_weight", "id"],
            },
        ),
        migrations.CreateModel(
            name="GuildMissionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("retreated", "已撤退"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("selected_guest_count", models.PositiveSmallIntegerField(default=1, verbose_name="参战门客数")),
                ("ruby_reward", models.PositiveIntegerField(default=0, verbose_name="结算红宝石")),
                ("guest_ids", models.JSONField(blank=True, default=list, verbose_name="参战门客ID")),
                ("guest_snapshots", models.JSONField(blank=True, default=list, verbose_name="参战门客快照")),
                ("troop_loadout", models.JSONField(blank=True, default=dict, verbose_name="护院编队")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="开始时间")),
                ("battle_at", models.DateTimeField(blank=True, null=True, verbose_name="开战时间")),
                ("return_at", models.DateTimeField(blank=True, null=True, verbose_name="返程时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_runs",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_mission_runs",
                        to="guilds.guildmember",
                        verbose_name="发起成员",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_runs",
                        to="guilds.guildmissiontemplate",
                        verbose_name="任务模板",
                    ),
                ),
                (
                    "battle_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guild_mission_runs",
                        to="battle.battlereport",
                        verbose_name="战报",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会任务运行",
                "verbose_name_plural": "帮会任务运行",
                "db_table": "guild_mission_runs",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GuildTroopDonationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="捐赠数量")),
                ("donated_at", models.DateTimeField(auto_now_add=True, verbose_name="捐赠时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="troop_donation_logs",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="troop_donation_logs",
                        to="guilds.guildmember",
                        verbose_name="捐赠成员",
                    ),
                ),
                (
                    "troop_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guild_donation_logs",
                        to="battle.trooptemplate",
                        verbose_name="护院模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会护院捐赠日志",
                "verbose_name_plural": "帮会护院捐赠日志",
                "db_table": "guild_troop_donation_logs",
                "ordering": ["-donated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GuildTroopStorage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveIntegerField(default=0, verbose_name="库存数量")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="troop_storages",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "troop_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guild_storages",
                        to="battle.trooptemplate",
                        verbose_name="护院模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会护院库存",
                "verbose_name_plural": "帮会护院库存",
                "db_table": "guild_troop_storage",
                "ordering": ["guild_id", "troop_template_id"],
            },
        ),
        migrations.AddIndex(
            model_name="guildmissionrun",
            index=models.Index(fields=["guild", "status", "-started_at"], name="gmr_guild_status_st_idx"),
        ),
        migrations.AddConstraint(
            model_name="guildmissionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("guild",),
                name="gmr_one_active_per_guild_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="guildtroopdonationlog",
            index=models.Index(fields=["guild", "-donated_at"], name="gtdl_guild_donated_idx"),
        ),
        migrations.AddConstraint(
            model_name="guildtroopstorage",
            constraint=models.UniqueConstraint(fields=("guild", "troop_template"), name="gts_guild_tpl_uq"),
        ),
        migrations.RunPython(seed_guild_mission_templates, rollback_seed_guild_mission_templates),
    ]
