# Generated by Django 5.2.8 on 2026-04-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0013_add_guild_pvp_fields_and_guild_raid_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guilddonationlog",
            name="resource_type",
            field=models.CharField(
                choices=[("silver", "银两"), ("grain", "粮食"), ("gold_bar", "金条")],
                max_length=10,
                verbose_name="资源类型",
            ),
        ),
    ]
