# Generated by Django 5.2.8 on 2026-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0007_battlereport_replay_versions"),
        ("guilds", "0026_guild_raid_failure_and_replay"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="guildmissionrun",
            index=models.Index(fields=["status", "return_at", "id"], name="gmr_due_scan_idx"),
        ),
    ]
