# Generated by Django 5.2.8 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0027_performance_scan_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildmissionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "进行中"),
                    ("completed", "已完成"),
                    ("retreated", "已撤退"),
                    ("failed", "结算失败"),
                ],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
