# Generated by Django 5.2.8 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0028_guild_mission_failure_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildmissiontemplate",
            name="weekly_limit",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="同一帮会同一任务模板每个自然周最多发起次数",
                verbose_name="每周次数上限",
            ),
        ),
    ]
