# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0119_botprofile_band_semantics"),
        ("trade", "0008_shopstock_last_refresh_writable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="数量")),
                ("settlement_price", models.PositiveIntegerField(verbose_name="结算价（金条）")),
                ("total_winners", models.PositiveIntegerField(default=1, verbose_name="中标人数")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待交付"), ("delivered", "已交付")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[("message_attachment", "消息附件"), ("direct_inventory", "直接入库")],
                        max_length=32,
                        verbose_name="交付方式",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="尝试次数")),
                ("last_error", models.TextField(blank=True, verbose_name="最近错误")),
                ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="交付时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="trade.auctionbid",
                        verbose_name="中标出价",
                    ),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auction_deliveries",
                        to="gameplay.itemtemplate",
                        verbose_name="物品模板",
                    ),
                ),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_deliveries",
                        to="gameplay.manor",
                        verbose_name="庄园",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auction_deliveries",
                        to="gameplay.message",
                        verbose_name="交付消息",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="trade.auctionslot",
                        verbose_name="拍卖位",
                    ),
                ),
            ],
            options={
                "verbose_name": "拍卖交付",
                "verbose_name_plural": "拍卖交付",
                "db_table": "trade_auction_delivery",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="trade_aucti_status_648003_idx"),
                    models.Index(fields=["manor", "status"], name="trade_aucti_manor_i_fbe1bf_idx"),
                    models.Index(fields=["slot", "status"], name="trade_aucti_slot_id_a4f521_idx"),
                ],
            },
        ),
    ]
