# Generated by Django 5.2.8 on 2026-07-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0009_auctiondelivery"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auctiondelivery",
            new_name="trade_aucti_status_041c3d_idx",
            old_name="trade_aucti_status_648003_idx",
        ),
        migrations.RenameIndex(
            model_name="auctiondelivery",
            new_name="trade_aucti_manor_i_ca3510_idx",
            old_name="trade_aucti_manor_i_fbe1bf_idx",
        ),
        migrations.RenameIndex(
            model_name="auctiondelivery",
            new_name="trade_aucti_slot_id_414f93_idx",
            old_name="trade_aucti_slot_id_a4f521_idx",
        ),
    ]
