# Generated by Django 5.2.8 on 2026-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0062_guest_status_arena"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="passive_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
