# Generated by Django 5.2.8 on 2026-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0152_performance_scan_indexes"),
        ("guests", "0067_guest_training_remaining_seconds"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["status", "last_hp_recovery_at", "id"], name="guest_hp_recovery_scan_idx"),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["status", "injury_loyalty_processed_at", "id"], name="guest_injury_loyalty_idx"),
        ),
    ]
