# Generated by Django 5.2.6 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0174_bot_maintenance_completion_event"),
        ("guests", "0070_alter_guestskill_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestrecruitment",
            name="bot_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="virtual_guest_recruitments",
                to="gameplay.botprofile",
                verbose_name="虚拟玩家档案",
            ),
        ),
        migrations.AddField(
            model_name="guestrecruitment",
            name="operation_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name="招募操作 ID"),
        ),
        migrations.AddField(
            model_name="guestrecruitment",
            name="pool_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="卡池快照"),
        ),
        migrations.AddField(
            model_name="guestrecruitment",
            name="quota_date",
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="虚拟招募配额日期"),
        ),
        migrations.AddField(
            model_name="guestrecruitment",
            name="quota_ordinal",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="虚拟招募日计划序号"),
        ),
        migrations.AddField(
            model_name="guestrecruitment",
            name="salary_commitment",
            field=models.PositiveIntegerField(default=0, verbose_name="新增工资承诺"),
        ),
        migrations.AddField(
            model_name="guestrecruitment",
            name="source",
            field=models.CharField(
                choices=[("player", "真人玩家"), ("virtual", "虚拟玩家")],
                db_index=True,
                default="player",
                max_length=16,
                verbose_name="招募来源",
            ),
        ),
        migrations.AddIndex(
            model_name="guestrecruitment",
            index=models.Index(
                fields=["bot_profile", "source", "quota_date", "quota_ordinal"],
                name="guest_recruit_vp_quota_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="guestrecruitment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "player"),
                        ("bot_profile__isnull", True),
                        ("operation_id__isnull", True),
                        ("quota_date__isnull", True),
                        ("quota_ordinal__isnull", True),
                    ),
                    models.Q(
                        ("source", "virtual"),
                        ("bot_profile__isnull", False),
                        ("operation_id__isnull", False),
                        models.Q(("operation_id", ""), _negated=True),
                        ("quota_date__isnull", False),
                        ("quota_ordinal__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="guest_recruit_source_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="guestrecruitment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "virtual"),
                    ("bot_profile__isnull", False),
                    ("quota_date__isnull", False),
                    ("quota_ordinal__isnull", False),
                ),
                fields=("bot_profile", "source", "quota_date", "quota_ordinal"),
                name="uniq_virtual_guest_recruitment_quota_slot",
            ),
        ),
    ]
