# Generated by Django 5.2.8 on 2026-04-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_add_player_troop"),
        ("gameplay", "0105_scoutrecord_was_retreated"),
        ("guests", "0062_guest_status_arena"),
    ]

    operations = [
        migrations.AddField(
            model_name="manor",
            name="arena_coop_participation_date",
            field=models.DateField(
                blank=True, db_index=True, default=None, null=True, verbose_name="竞技场共斗参与次数日期"
            ),
        ),
        migrations.AddField(
            model_name="manor",
            name="arena_coop_participations_today",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="竞技场共斗今日参与次数"),
        ),
        migrations.CreateModel(
            name="ArenaCoopEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recruiting", "报名中"),
                            ("preparing", "准备中"),
                            ("running", "结算中"),
                            ("completed", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="recruiting",
                        max_length=16,
                    ),
                ),
                ("player_limit", models.PositiveSmallIntegerField(default=5)),
                ("guest_limit_per_entry", models.PositiveSmallIntegerField(default=3)),
                ("prepare_duration_seconds", models.PositiveIntegerField(default=120)),
                ("prepare_ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("boss_name", models.CharField(default="张无忌", max_length=64)),
                ("boss_template_key", models.SlugField(default="arena_gl_top_zhang_wuji_boss", max_length=64)),
                ("boss_initial_hp", models.PositiveIntegerField(default=0)),
                ("boss_remaining_hp", models.PositiveIntegerField(default=0)),
                ("boss_defeated", models.BooleanField(default=False)),
                ("enemy_snapshot", models.JSONField(blank=True, default=dict)),
                ("reward_snapshot", models.JSONField(blank=True, default=dict)),
                ("daily_rule_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "battle_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_coop_events",
                        to="battle.battlereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场共斗活动",
                "verbose_name_plural": "竞技场共斗活动",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["status", "prepare_ends_at"], name="arena_coop_status_prepare_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "recruiting")),
                        fields=("status",),
                        name="unique_recruiting_arena_coop_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArenaCoopEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("registered", "报名中"), ("cancelled", "已撤销"), ("completed", "已完成")],
                        db_index=True,
                        default="registered",
                        max_length=16,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("seed_order", models.PositiveSmallIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="gameplay.arenacoopevent",
                    ),
                ),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_coop_entries",
                        to="gameplay.manor",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场共斗报名",
                "verbose_name_plural": "竞技场共斗报名",
                "ordering": ("joined_at",),
                "indexes": [models.Index(fields=["event", "status"], name="arena_coop_evt_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("event", "manor"), name="unique_arena_coop_event_manor")
                ],
            },
        ),
        migrations.CreateModel(
            name="ArenaCoopEntryGuest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slot_index", models.PositiveSmallIntegerField(default=0)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_guests",
                        to="gameplay.arenacoopentry",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_coop_entry_links",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场共斗报名门客",
                "verbose_name_plural": "竞技场共斗报名门客",
                "indexes": [models.Index(fields=["entry", "created_at"], name="arena_coop_ent_guest_entry_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("entry", "guest"), name="unique_arena_coop_entry_guest"),
                    models.UniqueConstraint(fields=("entry", "slot_index"), name="unique_arena_coop_entry_slot"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArenaCoopContribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_damage", models.PositiveIntegerField(default=0)),
                ("boss_damage", models.PositiveIntegerField(default=0)),
                ("guard_damage", models.PositiveIntegerField(default=0)),
                ("effective_damage", models.PositiveIntegerField(default=0)),
                ("damage_share_bps", models.PositiveIntegerField(default=0)),
                ("damage_rank", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ("met_minimum_contribution", models.BooleanField(default=False)),
                ("participation_coins", models.PositiveIntegerField(default=0)),
                ("damage_coins", models.PositiveIntegerField(default=0)),
                ("rank_coins", models.PositiveIntegerField(default=0)),
                ("clear_coins", models.PositiveIntegerField(default=0)),
                ("total_coins", models.PositiveIntegerField(default=0)),
                ("rare_drop_item_key", models.SlugField(blank=True, default="", max_length=64)),
                ("rare_drop_quantity", models.PositiveIntegerField(default=0)),
                ("rare_drop_granted", models.BooleanField(default=False)),
                ("reward_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution",
                        to="gameplay.arenacoopentry",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="gameplay.arenacoopevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场共斗贡献",
                "verbose_name_plural": "竞技场共斗贡献",
                "ordering": ("damage_rank", "id"),
                "indexes": [models.Index(fields=["event", "damage_rank"], name="arena_coop_contrib_rank_idx")],
            },
        ),
    ]
