# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0108_remove_style_probe_task_mission"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiontemplate",
            name="entry_cost",
            field=models.JSONField(blank=True, default=dict, help_text="任务入场消耗"),
        ),
    ]
