# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0109_missiontemplate_entry_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiontemplate",
            name="available_weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="任务开放星期，ISO weekday：1=周一，7=周日；空列表表示每日开放",
            ),
        ),
    ]
