# Generated by Django 5.2.8 on 2026-07-10 11:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0123_message_deletion_protection_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldChatSendAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_id", models.UUIDField(verbose_name="操作ID")),
                (
                    "message_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="消息ID"),
                ),
                ("text", models.CharField(max_length=200, verbose_name="消息文本")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发布"),
                            ("published", "已发布"),
                            ("refund_pending", "待退款"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("trumpet_consumed", models.BooleanField(default=False, verbose_name="已消耗小喇叭")),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="尝试次数")),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="发布时间")),
                ("refunded_at", models.DateTimeField(blank=True, null=True, verbose_name="退款时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_chat_send_attempts",
                        to="gameplay.manor",
                        verbose_name="庄园",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_chat_send_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "世界聊天发送记录",
                "verbose_name_plural": "世界聊天发送记录",
                "indexes": [models.Index(fields=["status", "created_at"], name="world_chat_status_created_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "operation_id"), name="world_chat_user_operation_uniq")
                ],
            },
        ),
    ]
