# Generated by Django 5.2.8 on 2026-07-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0138_add_cancelled_production_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotExternalStrengthReconciliation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile_id", models.PositiveBigIntegerField(db_index=True, verbose_name="虚拟玩家档案 ID")),
                ("domain_event_kind", models.CharField(max_length=64, verbose_name="领域事件类型")),
                ("domain_event_id", models.CharField(max_length=128, verbose_name="领域事件 ID")),
                ("origin_committed_at", models.DateTimeField(db_index=True, verbose_name="原事件提交时间")),
                ("pre_strength_summary", models.JSONField(default=dict, verbose_name="提交前强度摘要")),
                ("pre_prestige_band", models.CharField(max_length=32, verbose_name="提交前声望段")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_profile", "待档案对账"),
                            ("claimed_profile", "档案对账中"),
                            ("pending_population", "待人口交接"),
                            ("claimed_population", "人口交接中"),
                            ("applied", "已完成"),
                            ("quarantined", "已隔离"),
                        ],
                        default="pending_profile",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                ("profile_attempt_count", models.PositiveSmallIntegerField(default=0, verbose_name="档案阶段尝试次数")),
                (
                    "population_attempt_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="人口阶段尝试次数"),
                ),
                ("available_at", models.DateTimeField(db_index=True, verbose_name="下次可处理时间")),
                ("claim_token", models.UUIDField(blank=True, null=True, verbose_name="认领令牌")),
                ("claimed_at", models.DateTimeField(blank=True, null=True, verbose_name="认领时间")),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="认领过期时间")),
                ("profile_completed_at", models.DateTimeField(blank=True, null=True, verbose_name="档案阶段完成时间")),
                (
                    "population_handoff_completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="人口交接完成时间"),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True, verbose_name="最终完成时间")),
                ("result_summary", models.JSONField(blank=True, default=dict, verbose_name="结果摘要")),
                ("quarantined_at", models.DateTimeField(blank=True, null=True, verbose_name="隔离时间")),
                (
                    "quarantined_phase",
                    models.CharField(
                        blank=True,
                        choices=[("profile", "档案"), ("population", "人口")],
                        default="",
                        max_length=16,
                        verbose_name="隔离阶段",
                    ),
                ),
                ("failure_code", models.CharField(blank=True, default="", max_length=64, verbose_name="失败代码")),
                (
                    "last_error_digest",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="最近错误摘要"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "虚拟玩家外部强度对账",
                "verbose_name_plural": "虚拟玩家外部强度对账",
            },
        ),
        migrations.CreateModel(
            name="BotPolicyRelease",
            fields=[
                (
                    "version",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name="策略版本"),
                ),
                ("checksum", models.CharField(max_length=64, unique=True, verbose_name="策略校验和")),
                ("payload", models.JSONField(verbose_name="策略快照")),
                ("released_at", models.DateTimeField(verbose_name="发布时间")),
                ("retire_not_before", models.DateTimeField(verbose_name="最早退役时间")),
                ("retired_at", models.DateTimeField(blank=True, null=True, verbose_name="退役时间")),
            ],
            options={
                "verbose_name": "虚拟玩家策略发布",
                "verbose_name_plural": "虚拟玩家策略发布",
            },
        ),
        migrations.CreateModel(
            name="BotRuntimeRoutingState",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="virtual_players", editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                (
                    "bootstrap_mode",
                    models.CharField(
                        choices=[
                            ("legacy_before_gate", "Gate 前 V1"),
                            ("v2_active", "V2 已启用"),
                            ("v2_paused", "V2 已暂停"),
                        ],
                        default="legacy_before_gate",
                        max_length=24,
                        verbose_name="Bootstrap 模式",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.CharField(
                        choices=[
                            ("legacy_before_gate", "Gate 前 V1"),
                            ("v2_cutover", "V2 切换中"),
                            ("v2_active", "V2 已启用"),
                            ("v2_paused", "V2 已暂停"),
                        ],
                        default="legacy_before_gate",
                        max_length=24,
                        verbose_name="Maintenance 模式",
                    ),
                ),
                ("calibration_routes", models.JSONField(blank=True, default=list, verbose_name="参考校准路由")),
                ("revision", models.PositiveBigIntegerField(default=0, verbose_name="修订号")),
                (
                    "last_hourly_safety_window_end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最近小时安全窗口"),
                ),
                (
                    "last_daily_safety_window_end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最近日安全窗口"),
                ),
                (
                    "last_pause_window_id",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="最近暂停窗口 ID"),
                ),
                ("pause_reason", models.TextField(blank=True, default="", verbose_name="暂停原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "虚拟玩家运行路由",
                "verbose_name_plural": "虚拟玩家运行路由",
            },
        ),
        migrations.AddField(
            model_name="botprofile",
            name="development_profile",
            field=models.JSONField(blank=True, default=dict, verbose_name="发展画像"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="engine_version",
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name="执行器版本"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="forced_settlement_daily_budget",
            field=models.JSONField(blank=True, default=dict, verbose_name="强制结算日预算"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="last_strength_increase_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最近强度提升时间"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="maintenance_sequence",
            field=models.PositiveIntegerField(default=0, verbose_name="维护序号"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="plan_schema_version",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="发展画像版本"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="policy_checksum",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="策略校验和"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="policy_version",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="策略版本"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="rng_version",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="随机算法版本"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="strength_budget_entries",
            field=models.JSONField(blank=True, default=list, verbose_name="强度预算窗口"),
        ),
        migrations.AddField(
            model_name="botprofile",
            name="v2_enrolled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="V2 入组时间"),
        ),
        migrations.AddConstraint(
            model_name="botprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("engine_version__gte", 1)), name="bot_profile_engine_version_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="botprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("engine_version", 2), _negated=True),
                    models.Q(
                        ("rng_version__gte", 1),
                        ("plan_schema_version__gte", 1),
                        ("policy_version__gte", 1),
                        models.Q(("policy_checksum", ""), _negated=True),
                        ("last_strength_increase_at__isnull", False),
                        ("v2_enrolled_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bot_profile_v2_required_fields",
            ),
        ),
        migrations.AddIndex(
            model_name="botexternalstrengthreconciliation",
            index=models.Index(fields=["status", "available_at"], name="bot_ext_status_avail_idx"),
        ),
        migrations.AddIndex(
            model_name="botexternalstrengthreconciliation",
            index=models.Index(fields=["profile_id", "origin_committed_at", "id"], name="bot_ext_profile_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.UniqueConstraint(
                fields=("profile_id", "domain_event_kind", "domain_event_id"),
                name="bot_ext_reconcile_domain_event_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claim_token__isnull", True), ("claimed_at__isnull", True), ("claim_expires_at__isnull", True)
                    ),
                    models.Q(
                        ("claim_token__isnull", False),
                        ("claimed_at__isnull", False),
                        ("claim_expires_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bot_ext_reconcile_claim_fields_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("profile_attempt_count__lte", 12)), name="bot_ext_reconcile_profile_attempt_lte_12"
            ),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("population_attempt_count__lte", 12)), name="bot_ext_reconcile_pop_attempt_lte_12"
            ),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "applied"), ("applied_at__isnull", False)),
                    models.Q(models.Q(("status", "applied"), _negated=True), ("applied_at__isnull", True)),
                    _connector="OR",
                ),
                name="bot_ext_reconcile_applied_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("population_handoff_completed_at__isnull", True),
                    models.Q(
                        ("profile_completed_at__isnull", False),
                        ("applied_at__isnull", False),
                        ("population_handoff_completed_at__gte", models.F("profile_completed_at")),
                        ("applied_at__gte", models.F("population_handoff_completed_at")),
                    ),
                    _connector="OR",
                ),
                name="bot_ext_reconcile_handoff_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="botexternalstrengthreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "quarantined"),
                        ("quarantined_at__isnull", False),
                        models.Q(("quarantined_phase", ""), _negated=True),
                        models.Q(("failure_code", ""), _negated=True),
                    ),
                    models.Q(models.Q(("status", "quarantined"), _negated=True), ("quarantined_at__isnull", True)),
                    _connector="OR",
                ),
                name="bot_ext_reconcile_quarantine_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="botpolicyrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("checksum", ""), _negated=True), name="bot_policy_checksum_nonempty"
            ),
        ),
        migrations.AddConstraint(
            model_name="botpolicyrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("retire_not_before__gte", models.F("released_at"))),
                name="bot_policy_retire_deadline_gte_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="botpolicyrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retired_at__isnull", True), ("retired_at__gte", models.F("released_at")), _connector="OR"
                ),
                name="bot_policy_retired_at_gte_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("key", "virtual_players")), name="bot_runtime_routing_singleton_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("bootstrap_mode__in", ["legacy_before_gate", "v2_active", "v2_paused"])),
                name="bot_runtime_bootstrap_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maintenance_mode__in", ["legacy_before_gate", "v2_cutover", "v2_active", "v2_paused"])
                ),
                name="bot_runtime_maintenance_mode_valid",
            ),
        ),
    ]
