# Generated by Django 5.2.8 on 2026-07-27 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0139_botprofile_v2_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotPopulationRecomputeDemand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region", models.CharField(max_length=32, verbose_name="地区")),
                ("prestige_band", models.CharField(max_length=32, verbose_name="声望段")),
                ("requested_revision", models.PositiveBigIntegerField(default=0, verbose_name="请求修订号")),
                ("completed_revision", models.PositiveBigIntegerField(default=0, verbose_name="完成修订号")),
                ("claimed_revision", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="认领修订号")),
                ("claim_token", models.UUIDField(blank=True, null=True, verbose_name="认领令牌")),
                ("claimed_at", models.DateTimeField(blank=True, null=True, verbose_name="认领时间")),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="认领过期时间")),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="下次可处理时间"
                    ),
                ),
                ("consecutive_failure_count", models.PositiveIntegerField(default=0, verbose_name="连续失败次数")),
                (
                    "last_error_digest",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="最近错误摘要"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "虚拟玩家人口重算需求",
                "verbose_name_plural": "虚拟玩家人口重算需求",
                "indexes": [
                    models.Index(fields=["available_at", "claim_expires_at"], name="bot_pop_recompute_avail_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("region", "prestige_band"), name="bot_pop_recompute_cell_uniq"),
                    models.CheckConstraint(
                        condition=models.Q(("completed_revision__lte", models.F("requested_revision"))),
                        name="bot_pop_req_completed_lte",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("claimed_revision__isnull", True),
                                ("claim_token__isnull", True),
                                ("claimed_at__isnull", True),
                                ("claim_expires_at__isnull", True),
                            ),
                            models.Q(
                                ("claimed_revision__isnull", False),
                                ("claim_token__isnull", False),
                                ("claimed_at__isnull", False),
                                ("claim_expires_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="bot_pop_claim_fields_together",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("claimed_revision__isnull", True),
                            models.Q(
                                ("claimed_revision__gt", models.F("completed_revision")),
                                ("claimed_revision__lte", models.F("requested_revision")),
                            ),
                            _connector="OR",
                        ),
                        name="bot_pop_claim_revision_range",
                    ),
                ],
            },
        ),
    ]
