# Generated by Django 5.2.8 on 2026-07-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0140_bot_population_recompute_demand"),
    ]

    operations = [
        migrations.AddField(
            model_name="botruntimeroutingstate",
            name="policy_rollout_enabled",
            field=models.BooleanField(default=False, verbose_name="策略 rollout 已启用"),
        ),
        migrations.AddField(
            model_name="botruntimeroutingstate",
            name="policy_rollout_percent",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="策略 rollout 百分比"),
        ),
        migrations.AddField(
            model_name="botruntimeroutingstate",
            name="policy_rollout_target_version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="策略 rollout 目标版本"),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_rollout_target_version__gte", 1)), name="bot_runtime_policy_target_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_rollout_percent__lte", 100)), name="bot_runtime_policy_percent_lte_100"
            ),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("policy_rollout_enabled", True), ("policy_rollout_percent__gte", 1)),
                    models.Q(("policy_rollout_enabled", False), ("policy_rollout_percent", 0)),
                    _connector="OR",
                ),
                name="bot_runtime_policy_rollout_valid",
            ),
        ),
    ]
