# Generated by Django 5.2.8 on 2026-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0141_bot_runtime_policy_rollout"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSafetyMetricEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=128, unique=True, verbose_name="事件 ID")),
                ("metric_name", models.CharField(max_length=128, verbose_name="指标名")),
                ("occurred_at", models.DateTimeField(verbose_name="发生时间")),
                ("dimensions", models.JSONField(default=dict, verbose_name="规范维度")),
                ("value", models.DecimalField(decimal_places=12, max_digits=32, verbose_name="指标值")),
                ("payload_digest", models.CharField(max_length=64, verbose_name="载荷摘要")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="写入时间")),
            ],
            options={
                "verbose_name": "虚拟玩家安全指标事件",
                "verbose_name_plural": "虚拟玩家安全指标事件",
                "indexes": [
                    models.Index(fields=["occurred_at"], name="bot_safe_evt_occ_idx"),
                    models.Index(fields=["metric_name", "occurred_at"], name="bot_safe_evt_metric_occ_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("event_id", ""), _negated=True), name="bot_safety_event_id_nonempty"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("metric_name", ""), _negated=True), name="bot_safety_metric_nonempty"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payload_digest", ""), _negated=True),
                        name="bot_safety_event_digest_nonempty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BotSafetyMetricWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("window_id", models.CharField(max_length=128, unique=True, verbose_name="窗口 ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("hourly", "小时"), ("daily", "日")], max_length=8, verbose_name="窗口类型"
                    ),
                ),
                ("window_start_at", models.DateTimeField(verbose_name="窗口开始时间")),
                ("window_end_at", models.DateTimeField(db_index=True, verbose_name="窗口结束时间")),
                ("snapshot", models.JSONField(blank=True, default=dict, verbose_name="最终快照")),
                ("snapshot_digest", models.CharField(blank=True, default="", max_length=64, verbose_name="快照摘要")),
                ("finalized_at", models.DateTimeField(blank=True, null=True, verbose_name="冻结时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "虚拟玩家安全指标窗口",
                "verbose_name_plural": "虚拟玩家安全指标窗口",
                "indexes": [
                    models.Index(fields=["window_end_at", "kind"], name="bot_safe_win_end_kind_idx"),
                    models.Index(fields=["finalized_at", "window_end_at"], name="bot_safe_win_final_end_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "window_start_at"), name="bot_safety_window_kind_start_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("window_end_at__gt", models.F("window_start_at"))),
                        name="bot_safety_window_end_gt_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("finalized_at__isnull", True), ("snapshot_digest", "")),
                            models.Q(("finalized_at__isnull", False), models.Q(("snapshot_digest", ""), _negated=True)),
                            _connector="OR",
                        ),
                        name="bot_safety_window_finalize_fields",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("finalized_at__isnull", True),
                            ("finalized_at__gte", models.F("window_end_at")),
                            _connector="OR",
                        ),
                        name="bot_safety_window_final_gte_end",
                    ),
                ],
            },
        ),
    ]
