# Generated by Django 5.2.8 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0142_botsafetymetricevent_botsafetymetricwindow"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotArenaShortageBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("tournament", "普通竞技场"), ("coop", "共斗竞技场")],
                        max_length=16,
                        verbose_name="竞技场模式",
                    ),
                ),
                (
                    "prestige_band",
                    models.CharField(max_length=32, verbose_name="声望段"),
                ),
                (
                    "baseline_ratio",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=13,
                        verbose_name="短缺基线比例",
                    ),
                ),
                ("frozen_at", models.DateTimeField(verbose_name="冻结时间")),
                (
                    "evidence_id",
                    models.CharField(max_length=128, verbose_name="证据 ID"),
                ),
                (
                    "evidence_checksum",
                    models.CharField(max_length=64, verbose_name="证据校验和"),
                ),
                (
                    "payload_digest",
                    models.CharField(max_length=64, verbose_name="载荷摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="写入时间"),
                ),
            ],
            options={
                "verbose_name": "竞技场短缺基线",
                "verbose_name_plural": "竞技场短缺基线",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mode", "prestige_band"),
                        name="bot_arena_shortage_scope_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mode__in", ["tournament", "coop"])),
                        name="bot_arena_shortage_mode_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("baseline_ratio__gte", 0),
                            ("baseline_ratio__lte", 1),
                        ),
                        name="bot_arena_shortage_ratio_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("prestige_band", ""), _negated=True),
                        name="bot_arena_shortage_band_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("evidence_id", ""), _negated=True),
                        name="bot_arena_shortage_evid_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("evidence_checksum", ""), _negated=True),
                        name="bot_arena_shortage_cksum_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payload_digest", ""), _negated=True),
                        name="bot_arena_shortage_digest_nonempty",
                    ),
                ],
            },
        ),
    ]
