# Generated by Django 5.2.8 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0143_botarenashortagebaseline"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotMaintenanceExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(max_length=64, unique=True, verbose_name="操作 ID"),
                ),
                ("attempt_ordinal", models.PositiveIntegerField(verbose_name="提交尝试序号")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "定时维护"),
                            ("arena_acceleration", "竞技场加速"),
                            ("admin", "后台维护"),
                        ],
                        max_length=32,
                        verbose_name="触发来源",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("applied", "已执行"), ("no_action", "无动作")],
                        max_length=16,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "schedule_disposition",
                    models.CharField(
                        choices=[
                            ("advance_normal_schedule", "推进常规计划"),
                            ("preserve_normal_schedule", "保留常规计划"),
                        ],
                        max_length=32,
                        verbose_name="计划处理方式",
                    ),
                ),
                (
                    "maintenance_sequence_before",
                    models.PositiveIntegerField(verbose_name="执行前维护序号"),
                ),
                (
                    "maintenance_sequence_after",
                    models.PositiveIntegerField(verbose_name="执行后维护序号"),
                ),
                ("next_growth_at_before", models.DateTimeField(verbose_name="执行前下次成长时间")),
                ("next_growth_at_after", models.DateTimeField(verbose_name="执行后下次成长时间")),
                (
                    "action_kind",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="动作类型"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="结果原因"),
                ),
                ("request_digest", models.CharField(max_length=64, verbose_name="请求摘要")),
                ("requested_at", models.DateTimeField(verbose_name="请求时间")),
                (
                    "safety_started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="安全指标开始时间"),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True, verbose_name="提交时间")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_executions",
                        to="gameplay.botprofile",
                        verbose_name="虚拟玩家档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "虚拟玩家维护执行回执",
                "verbose_name_plural": "虚拟玩家维护执行回执",
            },
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_attempt_ordinal",
            field=models.PositiveIntegerField(default=0, verbose_name="成长尝试序号"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_claim_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="成长认领过期时间"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_claim_token",
            field=models.UUIDField(blank=True, null=True, verbose_name="成长认领令牌"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_claimed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="成长认领时间"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_demand_version",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="成长需求版本"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_guest_rarity_cap",
            field=models.CharField(blank=True, default="", max_length=16, verbose_name="成长门客稀有度上限"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_member_version",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="成长成员版本"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_minimum_guest_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="成长最低门客数"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_minimum_guest_level",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="成长最低门客等级"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_operation_id",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="成长操作 ID"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_power_before",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="成长前阵容战力"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_requested_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="成长请求时间"),
        ),
        migrations.AddConstraint(
            model_name="arenavirtualreservemember",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        models.Q(growth_claim_token__isnull=True)
                        & models.Q(growth_claimed_at__isnull=True)
                        & models.Q(growth_claim_expires_at__isnull=True)
                        & models.Q(growth_requested_at__isnull=True)
                        & models.Q(growth_operation_id="")
                        & models.Q(growth_attempt_ordinal=0)
                        & models.Q(growth_demand_version__isnull=True)
                        & models.Q(growth_member_version__isnull=True)
                        & models.Q(growth_power_before__isnull=True)
                        & models.Q(growth_minimum_guest_count__isnull=True)
                        & models.Q(growth_minimum_guest_level__isnull=True)
                        & models.Q(growth_guest_rarity_cap="")
                    )
                    | (
                        models.Q(growth_claim_token__isnull=False)
                        & models.Q(growth_claimed_at__isnull=False)
                        & models.Q(growth_claim_expires_at__isnull=False)
                        & models.Q(growth_requested_at__isnull=False)
                        & ~models.Q(growth_operation_id="")
                        & models.Q(growth_attempt_ordinal__gte=1)
                        & models.Q(growth_demand_version__isnull=False)
                        & models.Q(growth_member_version__isnull=False)
                        & models.Q(growth_power_before__isnull=False)
                        & models.Q(growth_minimum_guest_count__isnull=False)
                        & models.Q(growth_minimum_guest_level__isnull=False)
                    )
                ),
                name="arena_vm_growth_claim_fields_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="arenavirtualreservemember",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("growth_claim_expires_at__isnull", True))
                    | models.Q(("growth_claim_expires_at__gt", models.F("growth_claimed_at")))
                ),
                name="arena_vm_growth_claim_expiry_gt_claim",
            ),
        ),
        migrations.AddIndex(
            model_name="arenavirtualreservemember",
            index=models.Index(fields=["growth_claim_expires_at"], name="arena_vm_growth_claim_exp_idx"),
        ),
        migrations.AddConstraint(
            model_name="botmaintenanceexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation_id", ""), _negated=True),
                name="bot_maint_exec_operation_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenanceexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_ordinal__gte", 1)),
                name="bot_maint_exec_attempt_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenanceexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("maintenance_sequence_after__gte", models.F("maintenance_sequence_before"))),
                name="bot_maint_exec_sequence_nondecreasing",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenanceexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_digest", ""), _negated=True),
                name="bot_maint_exec_digest_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenanceexecution",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("trigger", "arena_acceleration"), _negated=True)
                    | models.Q(("schedule_disposition", "preserve_normal_schedule"))
                ),
                name="bot_maint_exec_arena_preserves_schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="botmaintenanceexecution",
            index=models.Index(
                fields=["profile", "completed_at"],
                name="bot_maint_exec_prof_idx",
            ),
        ),
    ]
