# Generated by Django 5.2.8 on 2026-08-01

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0145_alter_resourceevent_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenavirtualdemand",
            name="consecutive_failure_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="连续失败次数"),
        ),
        migrations.AddField(
            model_name="arenavirtualdemand",
            name="last_progress_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最近取得进展时间"),
        ),
        migrations.AddField(
            model_name="botruntimeroutingstate",
            name="safety_clean_window_streak",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="连续安全窗口数"),
        ),
        migrations.CreateModel(
            name="BotVirtualPlayerHealth",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="virtual_players",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "健康"),
                            ("degraded", "降级"),
                            ("recovering", "恢复中"),
                        ],
                        default="healthy",
                        max_length=16,
                    ),
                ),
                ("retryable_failure_streak", models.PositiveSmallIntegerField(default=0)),
                ("clean_success_streak", models.PositiveSmallIntegerField(default=0)),
                ("next_probe_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_failure_code", models.CharField(blank=True, default="", max_length=64)),
                ("last_error_digest", models.CharField(blank=True, default="", max_length=64)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_recovered_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "虚拟玩家健康状态",
                "verbose_name_plural": "虚拟玩家健康状态",
            },
        ),
        migrations.AddConstraint(
            model_name="botvirtualplayerhealth",
            constraint=models.CheckConstraint(
                condition=Q(key="virtual_players"),
                name="bot_vp_health_singleton_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="botvirtualplayerhealth",
            constraint=models.CheckConstraint(
                condition=Q(status__in=["healthy", "degraded", "recovering"]),
                name="bot_vp_health_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="botvirtualplayerhealth",
            constraint=models.CheckConstraint(
                condition=Q(retryable_failure_streak__lte=255) & Q(clean_success_streak__lte=255),
                name="bot_vp_health_streaks_lte_255",
            ),
        ),
    ]
