# Generated by Django 5.2.8 on 2026-08-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0148_bot_runtime_safety_window_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="botruntimeroutingstate",
            name="paused_from_maintenance_mode",
            field=models.CharField(blank=True, default="", max_length=24, verbose_name="暂停前运行模式"),
        ),
        migrations.AddConstraint(
            model_name="botruntimeroutingstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paused_from_maintenance_mode", ""),
                    ("paused_from_maintenance_mode__in", ["v2_cutover", "v2_active"]),
                    _connector="OR",
                ),
                name="bot_runtime_paused_from_maintenance_mode_valid",
            ),
        ),
    ]
