# Generated by Django 5.2.8 on 2026-08-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0149_botruntimeroutingstate_paused_from_maintenance_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botarenashortagebaseline",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="过期时间"),
        ),
        migrations.AddField(
            model_name="botarenashortagebaseline",
            name="max_real_entry_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="最大真实参赛人数"),
        ),
        migrations.AddField(
            model_name="botarenashortagebaseline",
            name="source",
            field=models.CharField(
                choices=[("pre_activation", "上线前冻结"), ("runtime_bootstrap", "运行时自动基线")],
                default="pre_activation",
                max_length=24,
                verbose_name="来源",
            ),
        ),
        migrations.AddConstraint(
            model_name="botarenashortagebaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["pre_activation", "runtime_bootstrap"])),
                name="bot_arena_shortage_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="botarenashortagebaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        ("max_real_entry_count__isnull", True),
                        ("source", "pre_activation"),
                    ),
                    models.Q(
                        ("expires_at__gt", models.F("frozen_at")),
                        ("expires_at__isnull", False),
                        ("max_real_entry_count__gte", 1),
                        ("max_real_entry_count__isnull", False),
                        ("source", "runtime_bootstrap"),
                    ),
                    _connector="OR",
                ),
                name="bot_arena_shortage_source_meta_shape",
            ),
        ),
    ]
