# Generated by Django 5.2.8 on 2026-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0151_manor_resource_updated_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["is_upgrading", "upgrade_complete_at", "id"], name="building_due_scan_idx"),
        ),
        migrations.AddIndex(
            model_name="playertechnology",
            index=models.Index(fields=["is_upgrading", "upgrade_complete_at", "id"], name="tech_due_scan_idx"),
        ),
    ]
