# Generated by Django 5.2.8 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0152_performance_scan_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_retry_reason",
            field=models.CharField(default="", blank=True, max_length=64, verbose_name="最近延期原因"),
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_retry_streak",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="成长延期连续次数"),
        ),
    ]
