# Generated by Django 5.2.8 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0153_arena_virtual_reserve_growth_retry_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arenavirtualdemand",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "协调中"),
                    ("satisfied", "已完成补位"),
                    ("blocked", "补位受阻"),
                    ("closed", "已关闭"),
                ],
                db_index=True,
                default="active",
                max_length=16,
                verbose_name="协调状态",
            ),
        ),
    ]
