# Generated by Django 5.2.8 on 2026-08-06

from django.db import migrations, models


def backfill_arena_virtual_demand_targets(apps, schema_editor) -> None:
    demand_model = apps.get_model("gameplay", "ArenaVirtualDemand")
    updates = []
    for demand in demand_model.objects.all().iterator(chunk_size=500):
        missing = max(0, int(demand.missing_entry_count or 0))
        reserve_target = max(0, int(demand.reserve_target_count or 0))
        if missing == 0:
            warm_target = 0
        else:
            warm_target = min(reserve_target, max(6, missing + (missing + 1) // 2))
        demand.warm_target_count = warm_target
        demand.last_input_change_at = demand.last_checked_at or demand.updated_at or demand.created_at
        updates.append(demand)
        if len(updates) >= 500:
            demand_model.objects.bulk_update(updates, ["warm_target_count", "last_input_change_at"])
            updates.clear()
    if updates:
        demand_model.objects.bulk_update(updates, ["warm_target_count", "last_input_change_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0154_alter_arenavirtualdemand_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenavirtualdemand",
            name="last_input_change_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最近需求输入变化时间"),
        ),
        migrations.AddField(
            model_name="arenavirtualdemand",
            name="warm_target_count",
            field=models.PositiveIntegerField(default=0, verbose_name="当前预热目标数"),
        ),
        migrations.RunPython(backfill_arena_virtual_demand_targets, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="arenavirtualdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(warm_target_count__lte=models.F("reserve_target_count")),
                name="arena_virtual_demand_warm_target_lte_reserve",
            ),
        ),
    ]
