# Generated by Django 5.2.8 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0155_arena_virtual_demand_activity_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="roster_target_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="虚拟阵容目标门客数",
            ),
        ),
    ]
