# Generated by Django 5.2.8 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0167_growth_control_snapshot_immutability"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualPlayerGrowthControlPointer",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="global",
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "虚拟玩家成长控制当前指针",
                "verbose_name_plural": "虚拟玩家成长控制当前指针",
            },
        ),
        migrations.CreateModel(
            name="VirtualPlayerGrowthControlRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_key", models.CharField(max_length=64, unique=True, verbose_name="运行 key")),
                ("control_date", models.DateField(verbose_name="控制日期")),
                ("policy_version", models.PositiveSmallIntegerField(default=2, verbose_name="Bot 策略版本")),
                ("policy_checksum", models.CharField(max_length=64, verbose_name="Bot 策略校验和")),
                ("source_sample_count", models.PositiveIntegerField(default=0, verbose_name="源样本数")),
                ("cell_count", models.PositiveIntegerField(default=0, verbose_name="单元格数")),
                ("fallback_count", models.PositiveIntegerField(default=0, verbose_name="fallback 单元格数")),
                ("run_digest", models.CharField(max_length=64, unique=True, verbose_name="运行摘要")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "执行中"), ("complete", "已完成"), ("failed", "已失败")],
                        default="running",
                        max_length=16,
                        verbose_name="运行状态",
                    ),
                ),
                ("failure_digest", models.CharField(blank=True, default="", max_length=64, verbose_name="失败摘要")),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=512, verbose_name="失败原因"),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("failed_at", models.DateTimeField(blank=True, null=True, verbose_name="失败时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="写入时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "虚拟玩家成长控制运行",
                "verbose_name_plural": "虚拟玩家成长控制运行",
            },
        ),
        migrations.RemoveConstraint(
            model_name="arenavirtualreservemember",
            name="arena_vm_growth_digest_schema_valid",
        ),
        migrations.AddField(
            model_name="arenavirtualreservemember",
            name="growth_policy_checksum",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="成长策略校验和"),
        ),
        migrations.AddConstraint(
            model_name="arenavirtualreservemember",
            constraint=models.CheckConstraint(
                condition=models.Q(growth_request_digest_schema__in=[1, 2, 3]),
                name="arena_vm_growth_digest_schema_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualplayergrowthcontrolrun",
            index=models.Index(fields=["control_date", "status"], name="bot_gctrl_run_date_idx"),
        ),
        migrations.AddIndex(
            model_name="virtualplayergrowthcontrolrun",
            index=models.Index(fields=["status", "updated_at"], name="bot_gctrl_run_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="virtualplayergrowthcontrolrun",
            constraint=models.CheckConstraint(
                condition=models.Q(policy_version=2), name="bot_growth_control_run_policy_v2"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualplayergrowthcontrolrun",
            constraint=models.CheckConstraint(
                condition=~models.Q(policy_checksum=""),
                name="bot_growth_control_run_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualplayergrowthcontrolrun",
            constraint=models.CheckConstraint(
                condition=~models.Q(run_digest=""),
                name="bot_growth_control_run_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualplayergrowthcontrolrun",
            constraint=models.CheckConstraint(
                condition=(models.Q(status="complete", completed_at__isnull=False) | ~models.Q(status="complete")),
                name="bot_growth_control_run_complete_marker",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualplayergrowthcontrolrun",
            constraint=models.CheckConstraint(
                condition=(models.Q(status="failed", failed_at__isnull=False) | ~models.Q(status="failed")),
                name="bot_growth_control_run_failed_marker",
            ),
        ),
        migrations.AddField(
            model_name="virtualplayergrowthcontrolpointer",
            name="current_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_pointers",
                to="gameplay.virtualplayergrowthcontrolrun",
                verbose_name="当前完整运行",
            ),
        ),
        migrations.AddField(
            model_name="virtualplayergrowthcontrolsnapshot",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshots",
                to="gameplay.virtualplayergrowthcontrolrun",
                verbose_name="完整运行",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualplayergrowthcontrolsnapshot",
            index=models.Index(
                fields=["run", "region", "prestige_band", "effective_until"],
                name="bot_growth_control_run_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualplayergrowthcontrolpointer",
            constraint=models.CheckConstraint(
                condition=models.Q(key="global"), name="bot_growth_control_pointer_global_only"
            ),
        ),
    ]
