# Generated by Django 5.2.8 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0168_virtualplayergrowthcontrolpointer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmaintenancerecovery",
            name="scope",
            field=models.CharField(
                choices=[
                    ("arena_member", "竞技场成员"),
                    ("arena_demand", "竞技场需求"),
                    ("profile", "虚拟玩家档案"),
                    ("population_cell", "人口单元格"),
                    ("guest", "门客"),
                ],
                max_length=24,
                verbose_name="恢复范围",
            ),
        ),
    ]
