# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0169_alter_botmaintenancerecovery_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arenavirtualreservemember",
            name="growth_rounds_started",
            field=models.PositiveIntegerField(default=0, verbose_name="已开始培养轮次"),
        ),
        migrations.AlterField(
            model_name="arenavirtualreservemember",
            name="growth_applied_action_count",
            field=models.PositiveIntegerField(default=0, verbose_name="已成功成长动作数"),
        ),
        migrations.AlterField(
            model_name="arenareservetrainingassignment",
            name="round_ordinal",
            field=models.PositiveIntegerField(verbose_name="培养轮次"),
        ),
        migrations.RemoveConstraint(
            model_name="arenareservetrainingassignment",
            name="arena_training_assignment_round_1_10",
        ),
        migrations.AddConstraint(
            model_name="arenareservetrainingassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(round_ordinal__gte=1),
                name="arena_training_assignment_round_positive",
            ),
        ),
        migrations.AlterField(
            model_name="botmaintenanceexecution",
            name="round_ordinal",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="培养轮次"),
        ),
        migrations.AlterField(
            model_name="botmaintenanceattempt",
            name="round_ordinal",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="培养轮次"),
        ),
        migrations.RemoveConstraint(
            model_name="botmaintenanceexecution",
            name="bot_maint_exec_slot_fields_together",
        ),
        migrations.AddConstraint(
            model_name="botmaintenanceexecution",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        round_ordinal__isnull=True,
                        action_ordinal_in_round__isnull=True,
                        slot_attempt_ordinal__isnull=True,
                    )
                    | (
                        models.Q(round_ordinal__gte=1)
                        & models.Q(action_ordinal_in_round__gte=1)
                        & models.Q(action_ordinal_in_round__lte=16)
                        & models.Q(slot_attempt_ordinal__gte=1)
                        & models.Q(slot_attempt_ordinal__lte=5)
                    )
                ),
                name="bot_maint_exec_slot_fields_together",
            ),
        ),
    ]
