# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0170_arena_growth_target_driven_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmaintenancecycle",
            name="current_action_state",
            field=models.CharField(
                choices=[
                    ("ready", "等待槽位"),
                    ("planning", "规划中"),
                    ("submitted", "已提交"),
                    ("no_action", "无动作"),
                    ("completed", "已完成"),
                    ("recovery", "待恢复"),
                ],
                default="ready",
                max_length=16,
                verbose_name="当前动作状态",
            ),
        ),
        migrations.AddField(
            model_name="botmaintenancecycle",
            name="last_action_completion_source",
            field=models.CharField(default="", max_length=32, blank=True, verbose_name="最近动作完成来源"),
        ),
        migrations.AddField(
            model_name="botmaintenancecycle",
            name="next_decision_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="下一次决策时间"),
        ),
        migrations.AddField(
            model_name="botmaintenancecycle",
            name="next_slot_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="下一槽位到期时间"),
        ),
        migrations.AddIndex(
            model_name="botmaintenancecycle",
            index=models.Index(fields=["profile", "status", "next_slot_due_at"], name="bot_maint_cycle_due_idx"),
        ),
    ]
