# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0171_bot_maintenance_cycle_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmaintenancecycle",
            name="interval_seed",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="槽位间隔种子"),
        ),
    ]
