# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models, transaction


def _freeze_current_admission_high_water(apps, _schema_editor) -> None:
    Demand = apps.get_model("gameplay", "ArenaVirtualDemand")
    demands = Demand.objects.annotate(current_member_count=models.Count("reserve_members")).iterator(chunk_size=200)
    batch = []
    for demand in demands:
        demand.admission_attempt_high_water = max(
            int(demand.admission_attempt_high_water or 0),
            int(demand.created_profile_count or 0),
            int(demand.current_member_count or 0),
        )
        batch.append(demand)
        if len(batch) >= 200:
            with transaction.atomic():
                Demand.objects.bulk_update(batch, ["admission_attempt_high_water"], batch_size=200)
            batch.clear()
    if batch:
        with transaction.atomic():
            Demand.objects.bulk_update(batch, ["admission_attempt_high_water"], batch_size=200)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("gameplay", "0172_bot_maintenance_cycle_interval_seed"),
    ]

    operations = [
        migrations.RunPython(
            _freeze_current_admission_high_water,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="arenavirtualdemand",
            name="created_profile_count",
        ),
        migrations.RemoveField(
            model_name="arenavirtualdemand",
            name="admission_legacy_exhausted_baseline_count",
        ),
        migrations.RemoveField(
            model_name="arenavirtualreservemember",
            name="accelerated_growth_rounds",
        ),
    ]
