# Generated by Django 5.2.8 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0173_remove_legacy_arena_lifecycle_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotMaintenanceCompletionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "domain_event_id",
                    models.CharField(max_length=160, unique=True, verbose_name="领域事件 ID"),
                ),
                (
                    "domain_event_kind",
                    models.CharField(
                        choices=[
                            ("building_upgrade", "建筑升级"),
                            ("technology_upgrade", "科技升级"),
                            ("guest_training", "门客训练"),
                            ("guest_recruitment", "门客招募"),
                        ],
                        max_length=32,
                        verbose_name="领域事件类型",
                    ),
                ),
                ("domain_object_id", models.PositiveBigIntegerField(verbose_name="领域对象 ID")),
                ("origin_completed_at", models.DateTimeField(db_index=True, verbose_name="领域完成时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待对账"), ("applied", "已对账")],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("available_at", models.DateTimeField(db_index=True, verbose_name="下次可处理时间")),
                ("attempt_count", models.PositiveSmallIntegerField(default=0, verbose_name="对账尝试次数")),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="对账完成时间")),
                ("result_summary", models.JSONField(blank=True, default=dict, verbose_name="对账结果摘要")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_completion_events",
                        to="gameplay.botprofile",
                        verbose_name="虚拟玩家档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "虚拟玩家维护完成事件",
                "verbose_name_plural": "虚拟玩家维护完成事件",
                "indexes": [
                    models.Index(
                        fields=["status", "available_at", "id"],
                        name="bot_maint_completion_due_idx",
                    ),
                    models.Index(
                        fields=["profile", "status", "origin_completed_at"],
                        name="bot_maint_completion_prof_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="botmaintenancecompletionevent",
            constraint=models.CheckConstraint(
                condition=~models.Q(domain_event_id=""),
                name="bot_maint_completion_event_id_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenancecompletionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(domain_object_id__gte=1),
                name="bot_maint_completion_object_id_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenancecompletionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(attempt_count__lte=32),
                name="bot_maint_completion_attempt_lte_32",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenancecompletionevent",
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(status="applied") & models.Q(processed_at__isnull=False))
                    | (~models.Q(status="applied") & models.Q(processed_at__isnull=True))
                ),
                name="bot_maint_completion_processed_fields",
            ),
        ),
    ]
