# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0174_bot_maintenance_completion_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="action_kind",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="动作类型"),
        ),
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="archetype",
            field=models.CharField(blank=True, db_index=True, default="", max_length=16, verbose_name="类型快照"),
        ),
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="grain_cost",
            field=models.PositiveBigIntegerField(default=0, verbose_name="粮食影子消耗"),
        ),
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="reason_category",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="原因分类"),
        ),
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="salary_runway_days",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="工资 runway 天数"),
        ),
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="salary_runway_silver",
            field=models.PositiveBigIntegerField(default=0, verbose_name="工资 runway 银两"),
        ),
        migrations.AddField(
            model_name="botmaintenanceattempt",
            name="silver_cost",
            field=models.PositiveBigIntegerField(default=0, verbose_name="银两影子消耗"),
        ),
        migrations.AddIndex(
            model_name="botexternalstrengthreconciliation",
            index=models.Index(fields=["profile_id", "status", "id"], name="bot_ext_profile_status_idx"),
        ),
        migrations.AddIndex(
            model_name="botmaintenanceattempt",
            index=models.Index(
                fields=["archetype", "action_kind", "outcome", "completed_at"],
                name="bot_maint_attempt_dims_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botmaintenancecycle",
            index=models.Index(
                fields=["profile", "trigger", "status", "-cycle_ordinal", "-id"],
                name="bot_maint_cycle_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botmaintenancerecovery",
            index=models.Index(
                fields=["scope", "entity_key", "status", "next_retry_at"],
                name="bot_maint_recovery_entity_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botprofile",
            index=models.Index(
                fields=["engine_version", "policy_version", "state", "next_growth_at", "id"],
                name="bot_due_identity_idx",
            ),
        ),
    ]
