# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models, transaction
from django.db.models import Count, Q

HIGH_COST_ACTION_KINDS = (
    "building_upgrade",
    "technology_upgrade",
    "training",
    "troop_recruitment",
)


def _backfill_high_cost_action_counts(apps, _schema_editor) -> None:
    Cycle = apps.get_model("gameplay", "BotMaintenanceCycle")
    cycles = (
        Cycle.objects.annotate(
            committed_high_cost_count=Count(
                "attempts",
                filter=Q(
                    attempts__action_kind__in=HIGH_COST_ACTION_KINDS,
                    attempts__outcome="applied",
                ),
            )
        )
        .order_by("id")
        .iterator(chunk_size=200)
    )
    batch = []
    for cycle in cycles:
        cycle.high_cost_actions_used = min(
            int(cycle.max_actions),
            int(cycle.action_ordinal),
            int(cycle.committed_high_cost_count or 0),
        )
        batch.append(cycle)
        if len(batch) >= 200:
            with transaction.atomic():
                Cycle.objects.bulk_update(batch, ["high_cost_actions_used"], batch_size=200)
            batch.clear()
    if batch:
        with transaction.atomic():
            Cycle.objects.bulk_update(batch, ["high_cost_actions_used"], batch_size=200)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("gameplay", "0175_botmaintenanceattempt_action_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="next_recruitment_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="下次招募到期时间"),
        ),
        migrations.AddField(
            model_name="botmaintenancecycle",
            name="high_cost_actions_used",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="已提交高价动作数"),
        ),
        migrations.AddIndex(
            model_name="botprofile",
            index=models.Index(
                fields=["engine_version", "policy_version", "state", "next_recruitment_at", "id"],
                name="bot_recruit_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenancecycle",
            constraint=models.CheckConstraint(
                condition=Q(high_cost_actions_used__lte=models.F("max_actions")),
                name="bot_maint_cycle_high_cost_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="botmaintenancecycle",
            constraint=models.CheckConstraint(
                condition=Q(high_cost_actions_used__lte=models.F("action_ordinal")),
                name="bot_maint_cycle_high_cost_lte_ordinal",
            ),
        ),
        migrations.RunPython(_backfill_high_cost_action_counts, migrations.RunPython.noop),
    ]
