# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0176_virtual_player_recruitment_due_and_cycle_budget"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="botmaintenanceattempt",
            name="bot_maint_attempt_dims_idx",
        ),
        migrations.AddIndex(
            model_name="botmaintenanceattempt",
            index=models.Index(
                fields=["archetype", "trigger", "action_kind", "outcome", "completed_at"],
                name="bot_maint_attempt_dims_idx",
            ),
        ),
    ]
