# Generated by Django 5.2.8 on 2026-08-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0182_alter_resourceevent_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manor",
            name="storage_capacity",
        ),
    ]
