# Generated by Django 5.2.8 on 2026-08-22

from django.db import migrations, models


def set_initial_mission_display_order(apps, schema_editor):
    mission_template = apps.get_model("gameplay", "MissionTemplate")
    mission_template.objects.filter(key="jingyanggang").update(display_order=1)
    mission_template.objects.filter(key="huashan_lunjian").update(display_order=2)


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0183_remove_manor_storage_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiontemplate",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=1000, verbose_name="显示顺序"),
        ),
        migrations.RunPython(set_initial_mission_display_order, migrations.RunPython.noop),
    ]
