# Generated by Django 5.2.8 on 2026-08-24

from django.db import migrations, models


def set_restricted_mission_card_limits(apps, schema_editor):
    mission_template = apps.get_model("gameplay", "MissionTemplate")
    mission_template.objects.filter(key="jiguanshou_chuxian").update(mission_card_daily_limit=1)
    mission_template.objects.filter(key="taozi_fenban").update(mission_card_daily_limit=0)


def restore_default_mission_card_limits(apps, schema_editor):
    mission_template = apps.get_model("gameplay", "MissionTemplate")
    mission_template.objects.filter(key__in=("jiguanshou_chuxian", "taozi_fenban")).update(mission_card_daily_limit=5)


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0186_update_intermediate_work_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiontemplate",
            name="mission_card_daily_limit",
            field=models.PositiveIntegerField(default=5, help_text="该任务每日最多使用的任务卡数量"),
        ),
        migrations.RunPython(set_restricted_mission_card_limits, restore_default_mission_card_limits),
    ]
