# Generated by Django 5.2.8 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0187_missiontemplate_mission_card_daily_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missiontemplate",
            name="mission_card_daily_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="该任务每日最多使用的任务卡数量",
                verbose_name="任务卡每日上限",
            ),
        ),
    ]
