from django.urls import path

from .views.arena import (
    ArenaCoopEventDetailView,
    ArenaEventDetailView,
    ArenaEventsView,
    ArenaExchangePageView,
    ArenaView,
    arena_cancel_view,
    arena_coop_cancel_view,
    arena_coop_register_view,
    arena_exchange_view,
    arena_register_view,
    refresh_arena_activity_api,
)
from .views.buildings import RepairCityDefenseView, UpgradeBuildingView, refresh_building_upgrades_api
from .views.core import DashboardView, GuideView, RankingView, SettingsView, rename_manor_view
from .views.inventory import (
    RecruitmentHallView,
    WarehouseView,
    move_item_to_treasury_view,
    move_item_to_warehouse_view,
    refresh_recruitment_hall_api,
    use_guest_rarity_upgrade_view,
    use_guest_rebirth_card_view,
    use_item_view,
    use_soul_container_view,
    use_xidianka_view,
    use_xisuidan_view,
)
from .views.jail import (
    JailView,
    OathGroveView,
    add_oath_bond_api,
    add_oath_bond_view,
    draw_pie_api,
    draw_pie_view,
    interact_prisoner_api,
    jail_status_api,
    oath_status_api,
    observe_prisoner_api,
    recruit_prisoner_api,
    recruit_prisoner_view,
    release_prisoner_api,
    release_prisoner_view,
    remove_oath_bond_api,
    remove_oath_bond_view,
    resolve_jail_milestone_api,
)
from .views.luanwu_shop import LuanwuShopView, purchase_luanwu_shop_item_view
from .views.map import (
    MapView,
    RaidConfigView,
    manor_detail_api,
    map_backfill_request_api,
    map_search_api,
    protection_status_api,
    raid_status_api,
    refresh_raid_activity_api,
    retreat_raid_api,
    start_raid_api,
    start_scout_api,
)
from .views.messages import (
    MessageListView,
    claim_attachment_view,
    delete_all_messages_view,
    delete_messages_view,
    mark_all_messages_read_view,
    mark_messages_read_view,
    view_message,
)
from .views.missions import (
    AcceptMissionView,
    TaskBoardView,
    refresh_mission_runs_api,
    retreat_mission_view,
    retreat_scout_view,
    use_mission_card_view,
)
from .views.production import (
    ForgeView,
    RanchView,
    SmithyView,
    StableView,
    cancel_equipment_forging_view,
    cancel_horse_production_view,
    cancel_livestock_production_view,
    cancel_smelting_production_view,
    decompose_equipment_view,
    refresh_production_runtime_api,
    start_equipment_forging_view,
    start_horse_production_view,
    start_livestock_production_view,
    start_smelting_production_view,
    synthesize_blueprint_equipment_view,
)
from .views.recruitment import (
    TroopRecruitmentView,
    deposit_troop_to_bank_view,
    refresh_troop_recruitments_api,
    start_troop_recruitment_view,
    withdraw_troop_from_bank_view,
)
from .views.technology import TechnologyView, refresh_technology_upgrades_api, upgrade_technology_view
from .views.work import (
    WorkView,
    assign_work_view,
    claim_work_reward_view,
    recall_work_view,
    refresh_work_assignments_api,
)

app_name = "gameplay"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("buildings/<str:category>/", DashboardView.as_view(), name="buildings_category"),
    path("tasks/", TaskBoardView.as_view(), name="tasks"),
    path("arena/", ArenaView.as_view(), name="arena"),
    path("arena/events/", ArenaEventsView.as_view(), name="arena_events"),
    path("arena/events/<int:tournament_id>/", ArenaEventDetailView.as_view(), name="arena_event_detail"),
    path("arena/coop/<int:event_id>/", ArenaCoopEventDetailView.as_view(), name="arena_coop_detail"),
    path("arena/exchange/", ArenaExchangePageView.as_view(), name="arena_exchange_page"),
    path("arena/register/", arena_register_view, name="arena_register"),
    path("arena/cancel/", arena_cancel_view, name="arena_cancel"),
    path("arena/coop/register/", arena_coop_register_view, name="arena_coop_register"),
    path("arena/coop/cancel/", arena_coop_cancel_view, name="arena_coop_cancel"),
    path("arena/exchange/submit/", arena_exchange_view, name="arena_exchange"),
    path("api/arena/refresh/", refresh_arena_activity_api, name="refresh_arena_activity_api"),
    path("messages/", MessageListView.as_view(), name="messages"),
    path("messages/view/<int:pk>/", view_message, name="view_message"),
    path("messages/<int:pk>/claim/", claim_attachment_view, name="claim_attachment"),
    path("messages/delete/", delete_messages_view, name="delete_messages"),
    path("messages/delete-all/", delete_all_messages_view, name="delete_all_messages"),
    path("messages/mark/", mark_messages_read_view, name="mark_messages_read"),
    path("messages/mark-all/", mark_all_messages_read_view, name="mark_all_messages_read"),
    path("warehouse/", WarehouseView.as_view(), name="warehouse"),
    path("warehouse/use/<int:pk>/", use_item_view, name="use_item"),
    path("warehouse/use-rebirth-card/<int:pk>/", use_guest_rebirth_card_view, name="use_rebirth_card"),
    path("warehouse/use-rarity-upgrade/<int:pk>/", use_guest_rarity_upgrade_view, name="use_guest_rarity_upgrade"),
    path("warehouse/use-soul-container/<int:pk>/", use_soul_container_view, name="use_soul_container"),
    path("warehouse/use-xisuidan/<int:pk>/", use_xisuidan_view, name="use_xisuidan"),
    path("warehouse/use-xidianka/<int:pk>/", use_xidianka_view, name="use_xidianka"),
    path("warehouse/move-to-treasury/<int:pk>/", move_item_to_treasury_view, name="move_to_treasury"),
    path("warehouse/move-to-warehouse/<int:pk>/", move_item_to_warehouse_view, name="move_to_warehouse"),
    path("luanwu-shop/", LuanwuShopView.as_view(), name="luanwu_shop"),
    path("luanwu-shop/purchase/", purchase_luanwu_shop_item_view, name="purchase_luanwu_shop_item"),
    path("recruitment/", RecruitmentHallView.as_view(), name="recruitment_hall"),
    path("api/recruitment/refresh/", refresh_recruitment_hall_api, name="refresh_recruitment_hall_api"),
    path("building/<int:pk>/upgrade/", UpgradeBuildingView.as_view(), name="upgrade_building"),
    path("building/<int:pk>/repair-city-defense/", RepairCityDefenseView.as_view(), name="repair_city_defense"),
    path("api/buildings/upgrades/refresh/", refresh_building_upgrades_api, name="refresh_building_upgrades_api"),
    path("tasks/accept/", AcceptMissionView.as_view(), name="accept_mission"),
    path("tasks/use-card/", use_mission_card_view, name="use_mission_card"),
    path("missions/<int:pk>/retreat/", retreat_mission_view, name="mission_retreat"),
    path("api/missions/refresh/", refresh_mission_runs_api, name="refresh_mission_runs_api"),
    path("technology/", TechnologyView.as_view(), name="technology"),
    path("technology/upgrade/<str:tech_key>/", upgrade_technology_view, name="upgrade_technology"),
    path("api/technology/upgrades/refresh/", refresh_technology_upgrades_api, name="refresh_technology_upgrades_api"),
    path("work/", WorkView.as_view(), name="work"),
    path("work/assign/", assign_work_view, name="assign_work"),
    path("work/recall/<int:pk>/", recall_work_view, name="recall_work"),
    path("work/claim/<int:pk>/", claim_work_reward_view, name="claim_work_reward"),
    path("api/work/refresh/", refresh_work_assignments_api, name="refresh_work_assignments_api"),
    path("stable/", StableView.as_view(), name="stable"),
    path("stable/produce/", start_horse_production_view, name="start_horse_production"),
    path(
        "stable/production/<int:production_id>/cancel/",
        cancel_horse_production_view,
        name="cancel_horse_production",
    ),
    path("ranch/", RanchView.as_view(), name="ranch"),
    path("ranch/produce/", start_livestock_production_view, name="start_livestock_production"),
    path(
        "ranch/production/<int:production_id>/cancel/",
        cancel_livestock_production_view,
        name="cancel_livestock_production",
    ),
    path("smithy/", SmithyView.as_view(), name="smithy"),
    path("smithy/produce/", start_smelting_production_view, name="start_smelting_production"),
    path(
        "smithy/production/<int:production_id>/cancel/",
        cancel_smelting_production_view,
        name="cancel_smelting_production",
    ),
    path("forge/", ForgeView.as_view(), name="forge"),
    path("forge/start/", start_equipment_forging_view, name="start_equipment_forging"),
    path(
        "forge/production/<int:production_id>/cancel/",
        cancel_equipment_forging_view,
        name="cancel_equipment_forging",
    ),
    path("forge/synthesize/", synthesize_blueprint_equipment_view, name="synthesize_blueprint_equipment"),
    path("forge/decompose/", decompose_equipment_view, name="decompose_equipment"),
    path("api/production/refresh/", refresh_production_runtime_api, name="refresh_production_runtime_api"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("settings/rename/", rename_manor_view, name="rename_manor"),
    path("guide/", GuideView.as_view(), name="guide"),
    path("jail/", JailView.as_view(), name="jail"),
    path("jail/prisoner/<int:prisoner_id>/recruit/", recruit_prisoner_view, name="recruit_prisoner_view"),
    path("jail/prisoner/<int:prisoner_id>/draw-pie/", draw_pie_view, name="draw_pie_view"),
    path("jail/prisoner/<int:prisoner_id>/release/", release_prisoner_view, name="release_prisoner_view"),
    path("oath-grove/", OathGroveView.as_view(), name="oath_grove"),
    path("oath-grove/add/", add_oath_bond_view, name="add_oath_bond_view"),
    path("oath-grove/<int:guest_id>/remove/", remove_oath_bond_view, name="remove_oath_bond_view"),
    path("ranking/", RankingView.as_view(), name="ranking"),
    path("troop-recruitment/", TroopRecruitmentView.as_view(), name="troop_recruitment"),
    path("troop-recruitment/start/", start_troop_recruitment_view, name="start_troop_recruitment"),
    path("troop-recruitment/bank/deposit/", deposit_troop_to_bank_view, name="deposit_troop_to_bank"),
    path("troop-recruitment/bank/withdraw/", withdraw_troop_from_bank_view, name="withdraw_troop_from_bank"),
    path("api/troop-recruitment/refresh/", refresh_troop_recruitments_api, name="refresh_troop_recruitments_api"),
    # 地图与踢馆系统
    path("map/", MapView.as_view(), name="map"),
    path("map/raid/<int:target_id>/", RaidConfigView.as_view(), name="raid_config"),
    path("api/map/search/", map_search_api, name="map_search_api"),
    path("api/map/backfill/", map_backfill_request_api, name="map_backfill_request_api"),
    path("api/map/manor/<int:manor_id>/", manor_detail_api, name="manor_detail_api"),
    path("api/map/scout/", start_scout_api, name="start_scout_api"),
    path("scout/<int:pk>/retreat/", retreat_scout_view, name="scout_retreat"),
    path("api/map/raid/", start_raid_api, name="start_raid_api"),
    path("api/map/raid/<int:raid_id>/retreat/", retreat_raid_api, name="retreat_raid_api"),
    path("api/map/status/", raid_status_api, name="raid_status_api"),
    path("api/map/status/refresh/", refresh_raid_activity_api, name="refresh_raid_activity_api"),
    path("api/map/protection/", protection_status_api, name="protection_status_api"),
    # 监牢 / 结义林
    path("api/jail/status/", jail_status_api, name="jail_status_api"),
    path("api/jail/prisoner/<int:prisoner_id>/observe/", observe_prisoner_api, name="observe_prisoner_api"),
    path("api/jail/prisoner/<int:prisoner_id>/interact/", interact_prisoner_api, name="interact_prisoner_api"),
    path(
        "api/jail/prisoner/<int:prisoner_id>/milestone/",
        resolve_jail_milestone_api,
        name="resolve_jail_milestone_api",
    ),
    path("api/jail/prisoner/<int:prisoner_id>/recruit/", recruit_prisoner_api, name="recruit_prisoner_api"),
    path("api/jail/prisoner/<int:prisoner_id>/draw-pie/", draw_pie_api, name="draw_pie_api"),
    path("api/jail/prisoner/<int:prisoner_id>/release/", release_prisoner_api, name="release_prisoner_api"),
    path("api/oath/status/", oath_status_api, name="oath_status_api"),
    path("api/oath/add/", add_oath_bond_api, name="add_oath_bond_api"),
    path("api/oath/remove/", remove_oath_bond_api, name="remove_oath_bond_api"),
]
